//! Update module for checking and downloading APK updates from GitHub Releases.
//!
//! Security features:
//! - HTTPS-only transport via reqwest with rustls
//! - SHA-256 checksum verification of downloaded APKs
//! - Minisign cryptographic signature verification of checksums
//! - Semantic versioning to prevent rollback attacks
//! - Automatic abort on checksum or signature mismatch

use minisign_verify::{PublicKey, Signature};
use semver::Version;
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::io::{Read, Write};

/// GitHub repository for releases
const GITHUB_REPO: &str = "niltonperimneto/neocalc-android";

/// Minisign Public Key for verifying updates.
/// TODO: Replace with your actual public key generated by `minisign -G`
const MINISIGN_PUBLIC_KEY: &str = "RWSaE7i2GVxl9w6xy88JQhq4E+QH/msvu+eGL/YdWZ9e2Lv/vUhvLOQz";

/// Result of checking for updates
#[derive(uniffi::Enum, Clone, Debug)]
pub enum UpdateCheckResult {
    /// An update is available
    Available {
        version: String,
        download_url: String,
        checksum: Option<String>,
        release_notes: String,
    },
    /// App is up to date
    UpToDate,
    /// Error occurred during check
    Error { message: String },
}

/// Result of downloading an update
#[derive(uniffi::Enum, Clone, Debug)]
pub enum DownloadResult {
    /// Download completed successfully and checksum verified
    Success { file_path: String },
    /// Checksum verification failed - file was deleted
    ChecksumFailed { expected: String, actual: String },
    /// Download or I/O error
    Error { message: String },
}

/// GitHub Release API response structures
#[derive(Deserialize)]
struct GitHubRelease {
    tag_name: String,
    body: Option<String>,
    assets: Vec<GitHubAsset>,
}

#[derive(Deserialize)]
struct GitHubAsset {
    name: String,
    browser_download_url: String,
}

/// Check for updates from GitHub Releases
///
/// # Arguments
/// * `current_version` - Current app version (e.g., "v2024.02-1")
/// * `device_abi` - Device ABI (e.g., "arm64-v8a", "armeabi-v7a", "x86_64", "x86")
///                  Pass empty string to always use universal APK
#[uniffi::export]
pub fn check_for_updates(current_version: String, device_abi: String) -> UpdateCheckResult {
    let api_url = format!(
        "https://api.github.com/repos/{}/releases/latest",
        GITHUB_REPO
    );

    let client = match reqwest::blocking::Client::builder()
        .user_agent("NeoCalc-Android-App")
        .build()
    {
        Ok(c) => c,
        Err(e) => {
            return UpdateCheckResult::Error {
                message: e.to_string(),
            }
        }
    };

    // Fetch latest release metadata
    let response = match client
        .get(&api_url)
        .header("Accept", "application/vnd.github.v3+json")
        .send()
    {
        Ok(r) => r,
        Err(e) => {
            return UpdateCheckResult::Error {
                message: e.to_string(),
            }
        }
    };

    if !response.status().is_success() {
        return UpdateCheckResult::Error {
            message: format!("GitHub API returned {}", response.status()),
        };
    }

    let release: GitHubRelease = match response.json() {
        Ok(r) => r,
        Err(e) => {
            return UpdateCheckResult::Error {
                message: e.to_string(),
            }
        }
    };

    // Parse versions using semver
    let latest_str = release.tag_name.trim_start_matches('v');
    let current_str = current_version.trim_start_matches('v');

    let latest_ver = Version::parse(latest_str).map_err(|e| e.to_string());
    let current_ver = Version::parse(current_str).map_err(|e| e.to_string());

    // Rollback protection: Only allow update if latest > current
    match (latest_ver, current_ver) {
        (Ok(latest), Ok(current)) => {
            if latest <= current {
                return UpdateCheckResult::UpToDate;
            }
        }
        _ => {
            // Fallback to string comparison if semver parsing fails (e.g. legacy versions)
            if latest_str == current_str {
                return UpdateCheckResult::UpToDate;
            }
        }
    }

    // Find APK matching device ABI, with fallback to universal
    let mut arch_apk: Option<(&str, &str)> = None; // (url, filename)
    let mut universal_apk: Option<(&str, &str)> = None;
    let mut legacy_apk: Option<(&str, &str)> = None; // app-release.apk fallback
    let mut checksum_url: Option<&str> = None;
    let mut signature_url: Option<&str> = None;

    for asset in &release.assets {
        if asset.name == "SHA256SUMS.txt" || asset.name == "checksums.txt" {
            checksum_url = Some(&asset.browser_download_url);
        } else if asset.name.ends_with(".minisig") {
            signature_url = Some(&asset.browser_download_url);
        } else if asset.name.ends_with(".apk") {
            // Match architecture-specific APK
            if !device_abi.is_empty() && asset.name.contains(&device_abi) {
                arch_apk = Some((&asset.browser_download_url, &asset.name));
            }
            // Universal APK (fallback 1)
            if asset.name.contains("universal") {
                universal_apk = Some((&asset.browser_download_url, &asset.name));
            }
            // Legacy naming (fallback 2)
            if asset.name == "app-release.apk" {
                legacy_apk = Some((&asset.browser_download_url, &asset.name));
            }
        }
    }

    // Priority: arch-specific > universal > legacy
    let (download_url, apk_filename) = arch_apk
        .or(universal_apk)
        .or(legacy_apk)
        .map(|(url, name)| (url.to_string(), name.to_string()))
        .unwrap_or_else(|| {
            return ("".to_string(), "".to_string());
        });

    if download_url.is_empty() {
        return UpdateCheckResult::Error {
            message: "No compatible APK found in release assets".to_string(),
        };
    }

    // Verify signature and fetch checksum
    let checksum = if let (Some(chk_url), Some(sig_url)) = (checksum_url, signature_url) {
        match verify_and_fetch_checksums(&client, chk_url, sig_url) {
            Ok(content) => parse_checksum(&content, &apk_filename),
            Err(e) => {
                return UpdateCheckResult::Error {
                    message: format!("Signature verification failed: {}", e),
                }
            }
        }
    } else {
        // SECURITY TODO: In strict mode, we should fail here if signature is missing
        None
    };

    UpdateCheckResult::Available {
        version: release.tag_name,
        download_url,
        checksum,
        release_notes: release.body.unwrap_or_default(),
    }
}

/// Verify Minisign signature of the checksum file
fn verify_and_fetch_checksums(
    client: &reqwest::blocking::Client,
    checksum_url: &str,
    signature_url: &str,
) -> Result<String, String> {
    // 0. Check if public key is configured
    if MINISIGN_PUBLIC_KEY.contains("REPLACE") {
        return Err("Public key not configured in app".to_string());
    }

    let pub_key =
        PublicKey::decode(MINISIGN_PUBLIC_KEY).map_err(|_| "Invalid public key format")?;

    // 1. Fetch signed content (SHA256SUMS.txt)
    let signed_content = client
        .get(checksum_url)
        .send()
        .map_err(|e| e.to_string())?
        .text()
        .map_err(|e| e.to_string())?;

    // 2. Fetch signature (SHA256SUMS.txt.minisig)
    let signature_str = client
        .get(signature_url)
        .send()
        .map_err(|e| e.to_string())?
        .text()
        .map_err(|e| e.to_string())?;
    let signature = Signature::decode(&signature_str).map_err(|_| "Invalid signature format")?;

    // 3. Verify
    pub_key
        .verify(signed_content.as_bytes(), &signature, false)
        .map_err(|_| "Cryptographic signature verification failed!".to_string())?;

    Ok(signed_content)
}

/// Parse checksum from verified content
fn parse_checksum(content: &str, target_filename: &str) -> Option<String> {
    for line in content.lines() {
        let parts: Vec<&str> = line.splitn(2, char::is_whitespace).collect();
        if parts.len() == 2 {
            let hash = parts[0].to_lowercase();
            let filename = parts[1].trim().trim_start_matches('*');
            if filename == target_filename || filename.ends_with(target_filename) {
                return Some(hash);
            }
        }
    }
    None
}

/// Download APK to specified path with optional progress callback
///
/// # Arguments
/// * `download_url` - URL to download from
/// * `output_path` - Local file path to save to
/// * `expected_checksum` - Optional SHA-256 checksum to verify
///
/// # Returns
/// * `DownloadResult::Success` if download and verification succeeded
/// * `DownloadResult::ChecksumFailed` if checksum doesn't match (file is deleted)
/// * `DownloadResult::Error` on any other failure
#[uniffi::export]
pub fn download_apk(
    download_url: String,
    output_path: String,
    expected_checksum: Option<String>,
) -> DownloadResult {
    let client = match reqwest::blocking::Client::builder()
        .user_agent("NeoCalc-Android-App")
        .build()
    {
        Ok(c) => c,
        Err(e) => {
            return DownloadResult::Error {
                message: e.to_string(),
            }
        }
    };

    // Start download
    let mut response = match client.get(&download_url).send() {
        Ok(r) => r,
        Err(e) => {
            return DownloadResult::Error {
                message: e.to_string(),
            }
        }
    };

    if !response.status().is_success() {
        return DownloadResult::Error {
            message: format!("Download failed: {}", response.status()),
        };
    }

    // Create output file
    let mut file = match std::fs::File::create(&output_path) {
        Ok(f) => f,
        Err(e) => {
            return DownloadResult::Error {
                message: e.to_string(),
            }
        }
    };

    // Download with streaming to avoid memory issues
    let mut buffer = [0u8; 8192];
    loop {
        match response.read(&mut buffer) {
            Ok(0) => break, // EOF
            Ok(n) => {
                if let Err(e) = file.write_all(&buffer[..n]) {
                    let _ = std::fs::remove_file(&output_path);
                    return DownloadResult::Error {
                        message: e.to_string(),
                    };
                }
            }
            Err(e) => {
                let _ = std::fs::remove_file(&output_path);
                return DownloadResult::Error {
                    message: e.to_string(),
                };
            }
        }
    }

    drop(file); // Ensure file is closed before verification

    // Verify checksum if provided
    if let Some(expected) = expected_checksum {
        let actual = match calculate_sha256(&output_path) {
            Ok(hash) => hash,
            Err(e) => {
                let _ = std::fs::remove_file(&output_path);
                return DownloadResult::Error { message: e };
            }
        };

        if actual.to_lowercase() != expected.to_lowercase() {
            // SECURITY: Delete potentially compromised file
            let _ = std::fs::remove_file(&output_path);
            return DownloadResult::ChecksumFailed { expected, actual };
        }
    }

    DownloadResult::Success {
        file_path: output_path,
    }
}

/// Calculate SHA-256 hash of a file
fn calculate_sha256(path: &str) -> Result<String, String> {
    let mut file = std::fs::File::open(path).map_err(|e| e.to_string())?;
    let mut hasher = Sha256::new();
    let mut buffer = [0u8; 8192];

    loop {
        match file.read(&mut buffer) {
            Ok(0) => break,
            Ok(n) => hasher.update(&buffer[..n]),
            Err(e) => return Err(e.to_string()),
        }
    }

    let result = hasher.finalize();
    Ok(format!("{:x}", result))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_check_for_updates_parses_response() {
        // This test requires network access; skip in CI if needed
        let result = check_for_updates("v0.0.1".to_string(), "arm64-v8a".to_string());

        // This test will now fail on signature verification because public key is placeholder
        // which is EXPECTED until user configures it.
        match result {
            UpdateCheckResult::Available { .. } => {
                // If signature verification was optional, this might pass
            }
            UpdateCheckResult::UpToDate => {}
            UpdateCheckResult::Error { message } => {
                // Should fail with "Public key not configured" or "No compatible APK"
                println!("Expected error: {}", message);
            }
        }
    }
}
